kind: Service
apiVersion: v1
metadata:
  name: ceph-nfs-rgw
  namespace: ceph
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    daemon: nfs-rgw
