---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: ceph
    daemon: rgw
  name: ceph-rgw
  namespace: ceph
spec:
  replicas: 1
  template:
    metadata:
      name: ceph-rgw
      namespace: ceph
      labels:
        app: ceph
        daemon: rgw
    spec:
      nodeSelector:
        node-type: storage
      serviceAccount: default
      volumes:
        - name: ceph-secrets
          secret:
            secretName: ceph-secrets-combined
        - name: ceph-conf
          configMap:
            name: ceph-conf
        - name: ceph-bootstrap-osd-keyring
          secret:
            secretName: ceph-bootstrap-osd-keyring
        - name: ceph-bootstrap-rgw-keyring
          secret:
            secretName: ceph-bootstrap-rgw-keyring
      containers:
        - name: ceph-rgw
          image: ceph/daemon:latest
          ports:
            - name: rgw-http
              containerPort: 8080
          env:
            - name: CEPH_DAEMON
              value: RGW
            - name: KV_TYPE
              value: k8s
            - name: CLUSTER
              value: ceph
          volumeMounts:
            - name: ceph-secrets
              mountPath: /etc/ceph/secrets
            - name: ceph-conf
              mountPath: /etc/ceph/conf
            - name: ceph-bootstrap-osd-keyring
              mountPath: /var/lib/ceph/bootstrap-osd
            - name: ceph-bootstrap-rgw-keyring
              mountPath: /var/lib/ceph/bootstrap-rgw
          livenessProbe:
              tcpSocket:
                port: 8080
              initialDelaySeconds: 60
              timeoutSeconds: 5
          readinessProbe:
              tcpSocket:
                port: 8080
              timeoutSeconds: 5
          resources:
            requests:
              memory: "10Mi"
              cpu: "250m"
            limits:
              memory: "50Mi"
              cpu: "500m"
