---
kind: PetSet
apiVersion: apps/v1alpha1
metadata:
  labels:
    app: ceph
    daemon: mon
  name: ceph-mon
  namespace: ceph
spec:
  serviceName: ceph-mon
  replicas: 3
  template:
    metadata:
      labels:
        app: ceph
        daemon: mon
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      nodeSelector:
        node-type: storage
        ceph-mon: "true"
      serviceAccount: default
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirst
      volumes:
        - name: ceph-conf
          secret:
            secretName: ceph-conf-combined
        - name: ceph-bootstrap-osd-keyring
          secret:
            secretName: ceph-bootstrap-osd-keyring
        - name: ceph-bootstrap-mds-keyring
          secret:
            secretName: ceph-bootstrap-mds-keyring
        - name: ceph-bootstrap-rgw-keyring
          secret:
            secretName: ceph-bootstrap-rgw-keyring
        - name: ceph-mon
          hostPath:
           path: /var/lib/ceph/mon
      containers:
        - name: ceph-mon
          image: quay.io/acaleph/ceph-daemon:10.2.3-trusty-1
          imagePullPolicy: Always
          securityContext:
            privileged: true
          ports:
            - containerPort: 6789
          env:
            - name: CEPH_DAEMON
              value: MON
            - name: KV_TYPE
              value: k8s
            - name: NETWORK_AUTO_DETECT
              value: "0"
            - name: CLUSTER
              value: ceph
            - name: MON_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MON_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CEPH_PUBLIC_NETWORK
              value: 10.0.0.0/8
            - name: CEPH_CLUSTER_NETWORK
              value: 10.0.0.0/8
          volumeMounts:
            - name: ceph-conf
              mountPath: /etc/ceph
            - name: ceph-bootstrap-osd-keyring
              mountPath: /var/lib/ceph/bootstrap-osd
            - name: ceph-bootstrap-mds-keyring
              mountPath: /var/lib/ceph/bootstrap-mds
            - name: ceph-bootstrap-rgw-keyring
              mountPath: /var/lib/ceph/bootstrap-rgw
            - name: ceph-mon
              mountPath: /var/lib/ceph/mon
          livenessProbe:
              tcpSocket:
                port: 6789
              initialDelaySeconds: 60
              timeoutSeconds: 5
          readinessProbe:
              tcpSocket:
                port: 6789
              timeoutSeconds: 5
          # resources:
          #   requests:
          #     memory: "50Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "100Mi"
          #     cpu: "500m"
