---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: ceph-exporter
  name: ceph-exporter
  namespace: ceph
spec:
  clusterIP: None
  ports:
  - name: ceph-exporter
    port: 9128
    protocol: TCP
  selector:
    app: ceph-exporter
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: ceph
  name: ceph-exporter
  annotations:
    prometheus.io/scrape: 'true'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ceph-exporter
    spec:
      containers:
      - name: ceph-exporter
        image: quay.io/acaleph/ceph_exporter:latest
        ports:
          - name: ceph-exporter
            containerPort: 9128
            hostPort: 9128
        volumeMounts:
          - name: ceph-secrets
            mountPath: /etc/ceph/secrets
          - name: ceph-conf
            mountPath: /etc/ceph/conf
      volumes:
        - name: ceph-secrets
          secret:
            secretName: ceph-secrets-combined
        - name: ceph-conf
          configMap:
            name: ceph-conf
